### ISSUE TITLE
Rename this project to scaffold'y name

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#1206]
This project provides scaffold for other projects. It may be better to rename it to something close to scaffold. Options:

1.  `drevops/scaffold`
2.  `drevops/drupal-scaffold`
3.  `drevops/template`
4.  `drevops/drupal-template`
5. `drevops/starter`
6. `drevops/drupal-starter`

**Comment by simesy** [comment]
Love a naming discussion. First. This is a good move because i always have to do a mental double take when I interpret what `drevops/drevops` does. it's pretty obvious when you read, however it could be more meaningful.

"scaffold" is an interesting one because it's defintely meaningful when applied to this project but it's not the same as "drupal core scaffolding" which applies the scaffold, rather than is the scaffold.

I would also consider drevops/base. For example when i was looking at cypress images, they have a cypress/base and that was very meaningful to me.

"template" and "starter" aren't bad. They imply that you are taking this and repurposing it. I understand you have scripts to apply updates later, but effectively the user is copying this right.  "starter-kit" or "starter", better than "template" as template is more abiguous and starterkit is a phrase used in Drupal core.

But... i don't really like "template" and "starter" in the spirit of this project, it's too... diminuitive?

So i vote for `drevops/scaffold` or `drevops/base`.

**Comment by richardgaunt** [comment]
My vote is for `drevops/scaffold`

**Comment by AlexSkrypnyk** [comment]
From AI:

> In the context of projects, particularly in software development, "scaffold" and "skeleton" both refer to foundational structures used to start new projects, but they imply slightly different approaches and contents:

> - **Scaffold**: This term suggests a more comprehensive framework or structure that not only provides the basic outline but also includes tools, scripts, and guidelines necessary to start building a project. It often comes with pre-configured setups for build processes, testing, and development environments, making it easier to jumpstart development without having to set up everything from scratch. A scaffold might include more detailed documentation and support files to guide the development process, aiming to speed up the initial setup and ensure consistency across projects.

> - **Skeleton**: Refers to a more minimalistic starting point for projects. It typically includes the bare minimum structure or template needed to start a project of a certain type. A skeleton might consist of a basic directory structure, essential configuration files, and possibly a minimal set of code files that define the standard structure of an application or software project. The focus here is on simplicity and providing a minimal framework that developers can build upon, without imposing too much structure or complexity from the outset.

> In essence, scaffolding provides a more detailed and comprehensive starting point, potentially with tools and scripts for common tasks, aimed at getting developers up and running quickly. A skeleton, on the other hand, offers a simpler and more stripped-down structure, giving developers the basics to start with and leaving more room for customization.
